imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

# Lyra

lyra_content:
    page:
        model: CMS\PageBundle\Entity\Page

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# LyraAdminBundle configuration
lyra_admin:
    theme: ui-lightness
    models:
        node:
            class: 'Lyra\ContentBundle\Entity\Node'
            controller: 'CMSNodeBundle:Admin'
            route_pattern_prefix: 'content'
            title: 'Contents'
            actions:
                move:
                    route_pattern: '{id}/move'
            fields:
                published:
                    get_method: isPublished
            list:
                default_sort:
                    field: lft
                    order: asc
                template: 'CMSNodeBundle:Admin:index.html.twig'
                title: Contents
                columns:
                    order:
                        template: 'CMSNodeBundle:Admin:order.html.twig'
                        sortable: false
                    title:
                        format_function: 'CMS\NodeBundle\Util\Util::formatNode'
                        sortable: false
                    published:
                        sortable: false
                batch_actions: []
        page:
            class: 'CMS\PageBundle\Entity\Page'
            controller: 'CMSPageBundle:Admin'
            title: false
            form:
                class: Lyra\ContentBundle\Form\PageFormType
                template: 'CMSPageBundle:Admin:form.html.twig'
                groups:
                    node:
                        embed: node
                        fields: [parent,title,link_title,path,published]
                    content:
                        fields: [content]
                        break_after: true
                    meta_tags:
                        caption: Meta tags
                        fields: [metaTitle,metaDescription,metaKeywords]
