# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

lyra_content_backend:
    resource: "@LyraContentBundle/Resources/config/routing/backend.yml"
    prefix: /admin

lyra_content_frontend:
    resource: "@LyraContentBundle/Resources/config/routing/frontend.yml"
